import { ContentContainer } from 'components/ContentContainer';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/pages/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Genesis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <header className={styles.header}>
          <ContentContainer>
            <h1>LCS</h1>
            <p>Xiojef</p>
          </ContentContainer>
        </header>

        <section className={styles.section}></section>
      </main>
    </div>
  );
};

export default Home;
