service: fullstack-website-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-west-2

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 4000

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
